#pragma once

#define WMS_EXCEPTION_CODE "WmsExceptionCode"
#define WMS_INVALID_FORMAT "InvalidFormat"
#define WMS_INVALID_CRS "InvalidCRS"
#define WMS_LAYER_NOT_DEFINED "LayerNotDefined"
#define WMS_STYLE_NOT_DEFINED "StyleNotDefined"
#define WMS_LAYER_NOT_QUERYABLE "LayerNotQueryable"
#define WMS_INVALID_POINT "InvalidPoint"
#define WMS_CURRENT_UPDATE_SEQUENCE "CurrentUpdateSequence"
#define WMS_INVALID_UPDATE_SEQUENCE "InvalidUpdateSequence"
#define WMS_MISSING_DIMENSION_VALUE "MissingDimensionValue"
#define WMS_INVALID_DIMENSION_VALUE "InvalidDimensionValue"
#define WMS_OPERATION_NOT_SUPPORTED "OperationNotSupported"
#define WMS_VOID_EXCEPTION_CODE "InvalidExceptionCode"
