#!/bin/bash
#
# Refresh or check the OGC schemas vendored under test/schemas.
#
#   update-schemas.sh          re-download everything (developer command, needs network)
#   update-schemas.sh --check  warn if upstream has changed since the vendored copies
#                              were taken; never fails, prints nothing when up to date
#                              or when the network is unavailable
#
# JSON schemas (ogcapi/) come from the OGC API - Common Part 2 draft in the
# ogcapi-common GitHub repository, pinned to OGCAPI_COMMON_SHA below. To move
# the pin, set the variable to the new commit (or "master" to look), run the
# update, review "git diff", then write the new SHA here.
#
# XML schemas (xsd/) are mirrored from schemas.opengis.net and www.w3.org.
#
# Both directories carry a VERSION file recording what was fetched and when;
# the README files describe the contents.

set -euo pipefail
cd "$(dirname "$0")"

OGCAPI_COMMON_REPO=opengeospatial/ogcapi-common
OGCAPI_COMMON_SHA=${OGCAPI_COMMON_SHA:-3828187a8fc5e98386743afcdd0c0d650855956f}
OGCAPI_COMMON_PATH=collections/openapi/schemas
# The schemas a collections response can reach; the download follows their $refs.
OGCAPI_ROOTS="common-geodata/collections.yaml common-geodata/collectionDesc-UAD.yaml"
LOCAL_WRAPPER=common-geodata/collections-UAD.yaml

SCHEMAS_OPENGIS=https://schemas.opengis.net
XSD_TREES="wms/1.3.0 wmts/1.0 ows/1.1.0 gml/3.1.1"
XSD_W3C="https://www.w3.org/1999/xlink.xsd https://www.w3.org/2001/xml.xsd"
# Representative files for the freshness check, one per tree
XSD_PROBES="wms/1.3.0/capabilities_1_3_0.xsd wmts/1.0/wmtsGetCapabilities_response.xsd ows/1.1.0/owsAll.xsd gml/3.1.1/base/gml.xsd"

CURL="curl -sS -f -L --max-time 20"
GITHUB_API=https://api.github.com/repos/$OGCAPI_COMMON_REPO

# ---------------------------------------------------------------- helpers

# Commit SHA and committer date of the pinned (or any) ref
github_commit() {  # ref -> "sha date"
  $CURL -H 'Accept: application/vnd.github+json' "$GITHUB_API/commits/$1" |
    python3 -c 'import json,sys; c=json.load(sys.stdin); print(c["sha"], c["commit"]["committer"]["date"][:10])'
}

# Newest commit that touched the schema directory on master
github_latest_schema_commit() {  # -> "sha date"
  $CURL -H 'Accept: application/vnd.github+json' \
    "$GITHUB_API/commits?path=$OGCAPI_COMMON_PATH&sha=master&per_page=1" |
    python3 -c 'import json,sys; c=json.load(sys.stdin)[0]; print(c["sha"], c["commit"]["committer"]["date"][:10])'
}

# Relative $ref targets of a YAML schema file (file paths only, not #fragments)
yaml_refs() {
  grep -o "\$ref: *['\"]\?[^'\" #][^'\" ]*" "$1" | sed -E "s/^\\\$ref: *['\"]?//" || true
}

# --------------------------------------------------------- JSON schemas

update_ogcapi() {
  read -r sha date < <(github_commit "$OGCAPI_COMMON_SHA")
  echo "ogcapi: fetching $OGCAPI_COMMON_PATH at $sha ($date)"
  local raw=https://raw.githubusercontent.com/$OGCAPI_COMMON_REPO/$sha/$OGCAPI_COMMON_PATH
  local tmp
  tmp=$(mktemp -d)
  # Breadth-first over $refs so the vendored closure is exactly what the roots need
  local queue=($OGCAPI_ROOTS) seen=" "
  while ((${#queue[@]})); do
    local rel=${queue[0]}; queue=("${queue[@]:1}")
    case "$seen" in *" $rel "*) continue;; esac
    seen+="$rel "
    mkdir -p "$tmp/$(dirname "$rel")"
    $CURL -o "$tmp/$rel" "$raw/$rel"
    local ref
    for ref in $(yaml_refs "$tmp/$rel"); do
      queue+=("$(realpath -m --relative-to="$tmp" "$tmp/$(dirname "$rel")/$ref")")
    done
  done
  echo "ogcapi: $(echo $seen | wc -w) files"

  # The local list wrapper is upstream collections.yaml with strict items
  {
    cat <<'HDR'
# LOCAL FILE (SmartMet), generated by update-schemas.sh; not part of the OGC schemas.
#
# Upstream collections.yaml describes each list item with collectionDesc.yaml,
# whose extent accepts additional dimensions that do not follow the Uniform
# Additional Dimensions (UAD) schema. This server implements UAD, so the list
# is validated with collectionDesc-UAD.yaml per item, the same schema used for
# /collections/{id}. Otherwise identical to collections.yaml.
HDR
    sed "s|'collectionDesc.yaml'|'collectionDesc-UAD.yaml'|" "$tmp/common-geodata/collections.yaml"
  } > "$tmp/$LOCAL_WRAPPER"
  grep -q "collectionDesc-UAD.yaml" "$tmp/$LOCAL_WRAPPER" ||
    { echo "ogcapi: ERROR: upstream collections.yaml no longer refers to collectionDesc.yaml; fix the wrapper" >&2; exit 1; }

  rm -rf ogcapi/common-geodata ogcapi/common-core ogcapi/records-core
  cp -r "$tmp"/. ogcapi/
  rm -rf "$tmp"
  printf 'repo %s\ncommit %s\ncommit-date %s\nfetched %s\n' \
    "$OGCAPI_COMMON_REPO" "$sha" "$date" "$(date -u +%F)" > ogcapi/VERSION
  sed -i -E "s|^Downloaded [0-9-]+ from commit [0-9a-f]+ \([0-9-]+\)\.|Downloaded $(date -u +%F) from commit ${sha:0:10} ($date).|" ogcapi/README.md
}

check_ogcapi() {
  local pinned latest latest_date
  pinned=$(awk '$1=="commit"{print $2}' ogcapi/VERSION 2>/dev/null) || return 0
  read -r latest latest_date < <(github_latest_schema_commit 2>/dev/null) || return 0
  [ -n "$latest" ] || return 0
  if [ "$latest" != "$pinned" ]; then
    echo "WARNING: OGC API Common Part 2 schemas: upstream $OGCAPI_COMMON_PATH changed on $latest_date (${latest:0:10});"
    echo "         vendored copy is ${pinned:0:10}. Review with OGCAPI_COMMON_SHA=$latest make update-schemas"
  fi
}

# ---------------------------------------------------------- XML schemas

update_xsd() {
  echo "xsd: mirroring $XSD_TREES from $SCHEMAS_OPENGIS"
  local tmp
  tmp=$(mktemp -d)
  local tree
  for tree in $XSD_TREES; do
    wget -q -r -np -nH -l 3 -A xsd -P "$tmp" "$SCHEMAS_OPENGIS/$tree/"
  done
  local url
  for url in $XSD_W3C; do
    $CURL -o "$tmp/$(basename "$url")" "$url"
  done
  echo "xsd: $(find "$tmp" -name '*.xsd' | wc -l) files"
  for tree in $XSD_TREES; do rm -rf "xsd/$tree"; done
  cp -r "$tmp"/. xsd/
  rm -rf "$tmp"
  printf 'source %s\nfetched %s\n' "$SCHEMAS_OPENGIS" "$(date -u +%F)" > xsd/VERSION
  sed -i -E "s|on [0-9]{4}-[0-9]{2}-[0-9]{2}\.$|on $(date -u +%F).|" xsd/README.md
}

check_xsd() {
  local fetched probe modified stale=""
  fetched=$(awk '$1=="fetched"{print $2}' xsd/VERSION 2>/dev/null) || return 0
  [ -n "$fetched" ] || return 0
  for probe in $XSD_PROBES; do
    modified=$($CURL -I "$SCHEMAS_OPENGIS/$probe" 2>/dev/null | awk -F': ' 'tolower($1)=="last-modified"{print $2}' | tr -d '\r') || continue
    [ -n "$modified" ] || continue
    if [ "$(date -u -d "$modified" +%F)" \> "$fetched" ]; then
      stale+=" $probe ($(date -u -d "$modified" +%F))"
    fi
  done
  if [ -n "$stale" ]; then
    echo "WARNING: OGC XML schemas changed upstream after the mirror of $fetched:$stale"
    echo "         Review with make update-schemas"
  fi
}

# ------------------------------------------------------------------ main

case "${1:-update}" in
  --check|check)
    # Never fail the tests over this; SMARTMET_SCHEMA_CHECK=0 disables it
    [ "${SMARTMET_SCHEMA_CHECK:-1}" = 0 ] && exit 0
    check_ogcapi || true
    check_xsd || true
    exit 0
    ;;
  update)
    update_ogcapi
    update_xsd
    echo
    echo "Validating the current test expectations against the refreshed schemas:"
    make -s -C .. validate-xml-schemas validate-tiles-schemas
    echo
    echo "Review the changes with: git status --short test/schemas; git diff test/schemas"
    ;;
  *)
    echo "usage: $0 [update|--check]" >&2; exit 2;;
esac
